# config for https://github.com/camunda-community-hub/camunda-8-benchmark
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  labels:
    app: benchmark
spec:
  selector:
    matchLabels:
      app: benchmark
  replicas: 12
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
      - name: benchmark
        image: upgradingdave/camunda-8-benchmark:main
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dzeebe.client.broker.gateway-address=camunda-zeebe-gateway:26500
              -Dzeebe.client.security.plaintext=true
              -Dzeebe.client.request-timeout=600s
              -Dzeebe.client.job.poll-interval=1ms
              -Dzeebe.client.worker.max-jobs-active=2000
              -Dbenchmark.startPiPerSecond=30
              -Dbenchmark.maxBackpressurePercentage=1.0
              -Dbenchmark.taskCompletionDelay=10
              -Dbenchmark.bpmnProcessId=process-8-service-tasks
              -Dbenchmark.jobType=benchmark-task
              -Dbenchmark.multipleJobTypes=8
              -Dbenchmark.payloadPath=bpmn/typical_payload.json
              -Dbenchmark.autoDeployProcess=false
              -Dbenchmark.warmupPhaseDurationMillis=60000
              -Dbenchmark.startRateAdjustmentStrategy=backpressure
              -Dbenchmark.startPiIncreaseFactor=0.5
        resources:
          limits:
            cpu: 14
            memory: 27Gi
          requests:
            cpu: 1
            memory: 1Gi