# config for https://github.com/camunda-community-hub/camunda-8-benchmark
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: benchmark-gateway-${BENCHMARK_ID}
  labels:
    app: benchmark-gateway-${BENCHMARK_ID}
spec:
  selector:
    matchLabels:
      app: benchmark-gateway-${BENCHMARK_ID}
  serviceName: benchmark-gateway-${BENCHMARK_ID}
  replicas: 1
  template:
    metadata:
#      annotations:
#        linkerd.io/inject: enabled
#        config.linkerd.io/opaque-ports: "26500"
      labels:
        app: benchmark-gateway-${BENCHMARK_ID}
#        istio.io/dataplane-mode: ambient
    spec:
      containers:
      - name: benchmark
        image: camundacommunityhub/camunda-8-benchmark:main
        imagePullPolicy: Always
        env:
          - name: BENCHMARK_STARTER_ID
            value: benchmark-gateway-${BENCHMARK_ID}
          - name: JAVA_OPTIONS
            value: >-
              -Dcamunda.client.mode=selfmanaged
              -Dcamunda.client.zeebe.grpc-address=http://${GATEWAY_IP}:26500            
              -Dcamunda.client.zeebe.prefer-rest-over-grpc=false
              -Dcamunda.client.zeebe.request-timeout=600s
              -Dcamunda.client.zeebe.defaults.poll-interval=1ms
              -Dcamunda.client.zeebe.default-job-worker-stream-enabled=true
              -Dcamunda.client.worker.defaults.stream-enabled=true
              -Dbenchmark.startProcesses=true
              -Dbenchmark.bpmnProcessId=${loadGeneratorStarter.processModel}
              -Dbenchmark.startPiPerSecond=${loadGeneratorStarter.startThroughput}
              -Dbenchmark.startPiIncreaseFactor=${loadGeneratorStarter.startPiIncreaseFactor}
              -Dbenchmark.startRateAdjustmentStrategy=${loadGeneratorStarter.rateAdjustmentStrategy}
              -Dbenchmark.fixedBackOffDelay=${jobWorker.fixedBackOffDelay}
              -Dbenchmark.maxBackpressurePercentage=1.0
              -Dbenchmark.startWorkers=true
              -Dbenchmark.jobType=benchmark-task
              -Dbenchmark.multipleJobTypes=${jobWorker.numberOfJobTypes}
              -Dbenchmark.taskCompletionDelay=${jobWorker.jobDuration}
              -Dbenchmark.payloadPath=file:/${loadGeneratorStarter.payload}
              -Dbenchmark.autoDeployProcess=false
              -Dbenchmark.warmupPhaseDurationMillis=${loadGeneratorStarter.rampUpTime}000
              -Dbenchmark.enablePartitionPinning=${jobWorker.partitionPinning}
              -Dbenchmark.partitionCount=${engine.partitions}
              -Dbenchmark.numberOfStarters=${loadGeneratorStarter.starterReplicas}
#              -Dcamunda.client.zeebe.grpc-address=http://camunda-zeebe-gateway-grpc:26500            
#              -Dzeebe.client.worker.max-jobs-active=${jobWorker.maxJobsActive}
#              -Dzeebe.client.worker.threads=${jobWorker.numberOfThreads}
        resources:
          limits:
            cpu: ${engine.vcpus}
            memory: ${engine.ram}Gi
          requests:
            cpu: 5
            memory: 5Gi
        volumeMounts:
        - name: payload
          mountPath: ${loadGeneratorStarter.payload}
          subPath: ${loadGeneratorStarter.payload}
          readOnly: true
      volumes:
      - name: payload
        configMap:
          name: payload
