# config for https://github.com/camunda-community-hub/camunda-8-benchmark
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  labels:
    app: benchmark
spec:
  selector:
    matchLabels:
      app: benchmark
  replicas: ${loadGeneratorStarter.starterReplicas}
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
      - name: benchmark
        image: upgradingdave/camunda-8-benchmark:main
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dzeebe.client.broker.gateway-address=camunda-zeebe-gateway:26500
              -Dzeebe.client.security.plaintext=true
              -Dzeebe.client.request-timeout=600s
              -Dzeebe.client.job.poll-interval=1ms
              -Dzeebe.client.worker.max-jobs-active=2000
              -Dbenchmark.startPiPerSecond=${loadGeneratorStarter.startThroughput}
              -Dbenchmark.maxBackpressurePercentage=1.0
              -Dbenchmark.taskCompletionDelay=${jobWorker.jobDuration}
              -Dbenchmark.bpmnProcessId=${loadGeneratorStarter.processModel}
              -Dbenchmark.jobType=benchmark-task
              -Dbenchmark.multipleJobTypes=${jobWorker.numberOfDifferentJobTypes}
              -Dbenchmark.payloadPath=bpmn/typical_payload.json
              -Dbenchmark.autoDeployProcess=false
              -Dbenchmark.warmupPhaseDurationMillis=${loadGeneratorStarter.rampUpTime}000
              -Dbenchmark.startRateAdjustmentStrategy=backpressure
              -Dbenchmark.startPiIncreaseFactor=0.4
        resources:
          limits:
            cpu: ${engine.vcpus}
            memory: ${engine.ram}Gi
          requests:
            cpu: 1
            memory: 1Gi
