# config for https://github.com/camunda-community-hub/camunda-8-benchmark
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  labels:
    app: benchmark
spec:
  selector:
    matchLabels:
      app: benchmark
  replicas: ${loadGeneratorStarter.starterReplicas}
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
      - name: benchmark
        image: camundacommunityhub/camunda-8-benchmark:main
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dcamunda.client.mode=selfmanaged
              -Dcamunda.client.zeebe.grpc-address=http://camunda-zeebe-gateway:26500            
              -Dcamunda.client.zeebe.prefer-rest-over-grpc=false
              -Dzeebe.client.request-timeout=600s
              -Dzeebe.client.job.poll-interval=1ms
              -Dcamunda.client.zeebe.default-job-worker-stream-enabled=true
              -Dbenchmark.startProcesses=true
              -Dbenchmark.bpmnProcessId=${loadGeneratorStarter.processModel}
              -Dbenchmark.startPiPerSecond=${loadGeneratorStarter.startThroughput}
              -Dbenchmark.startPiIncreaseFactor=${loadGeneratorStarter.startPiIncreaseFactor}
              -Dbenchmark.startRateAdjustmentStrategy=${loadGeneratorStarter.rateAdjustmentStrategy}
              -Dbenchmark.fixedBackOffDelay=${jobWorker.fixedBackOffDelay}
              -Dbenchmark.maxBackpressurePercentage=1.0
              -Dbenchmark.jobType=benchmark-task
              -Dbenchmark.multipleJobTypes=${jobWorker.numberOfJobTypes}
              -Dbenchmark.taskCompletionDelay=${jobWorker.jobDuration}
              -Dbenchmark.payloadPath=file:/${loadGeneratorStarter.payload}
              -Dbenchmark.autoDeployProcess=false
              -Dbenchmark.warmupPhaseDurationMillis=${loadGeneratorStarter.rampUpTime}000
#              -Dzeebe.client.worker.max-jobs-active=${jobWorker.maxJobsActive}
#              -Dzeebe.client.worker.threads=${jobWorker.numberOfThreads}
        resources:
          limits:
            cpu: ${engine.vcpus}
            memory: ${engine.ram}Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: payload
          mountPath: ${loadGeneratorStarter.payload}
          subPath: ${loadGeneratorStarter.payload}
          readOnly: true
      volumes:
      - name: payload
        configMap:
          name: payload
