# config for https://github.com/camunda-community-hub/camunda-8-benchmark
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark
  labels:
    app: benchmark
spec:
  selector:
    matchLabels:
      app: benchmark
  replicas: ${loadGeneratorStarter.starterReplicas}
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
      - name: benchmark
        image: gcr.io/camunda-researchanddevelopment/falko-camunda-8-benchmark:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS
            value: camunda-zeebe-gateway:26500
          - name: ZEEBE_CLIENT_SECURITY_PLAINTEXT
            value: "true"
          #- name: BENCHMARK_MESSAGESCENARIO
          #  value: "/scenario/msgscenario.json"
          - name: BENCHMARK_MESSAGESSCENARIOSPERSECOND
            value: "${loadGeneratorStarter.startThroughput}"
          - name: BENCHMARK_DELAYBETWEENMESSAGES
            value: "1"
          - name: BENCHMARK_MESSAGESLOADDURATION
            value: "${loadGeneratorStarter.runDuration}000"
          - name: BENCHMARK_STARTWORKERS
            value: "false"
          - name: BENCHMARK_TASKCOMPLETIONDELAY
            value: "1"
          - name: JAVA_OPTIONS
            value: >-
              -Dbenchmark.startProcesses=false
              -Dzeebe.client.broker.gateway-address=camunda-zeebe-gateway:26500
              -Dzeebe.client.security.plaintext=true
              -Dzeebe.client.request-timeout=600s
              -Dzeebe.client.job.poll-interval=1ms
              -Dzeebe.client.worker.max-jobs-active=${jobWorker.maxJobsActive}
              -Dbenchmark.startPiPerSecond=${loadGeneratorStarter.startThroughput}
              -Dbenchmark.maxBackpressurePercentage=1.0
              -Dbenchmark.taskCompletionDelay=${jobWorker.jobDuration}
              -Dbenchmark.bpmnProcessId=${loadGeneratorStarter.processModel}
              -Dbenchmark.jobType=benchmark-task
              -Dbenchmark.multipleJobTypes=${jobWorker.numberOfJobTypes}
              -Dbenchmark.messageScenario=msg-scenario.json
              -Dbenchmark.delayBetweenMessages=10
              -Dbenchmark.messagesLoadDuration=${loadGeneratorStarter.runDuration}000
              -Dbenchmark.autoDeployProcess=false
              -Dbenchmark.warmupPhaseDurationMillis=${loadGeneratorStarter.rampUpTime}000
              -Dbenchmark.startRateAdjustmentStrategy=${loadGeneratorStarter.rateAdjustmentStrategy}
              -Dbenchmark.startPiIncreaseFactor=${loadGeneratorStarter.startPiIncreaseFactor}
              -Dbenchmark.fixedBackOffDelay=${jobWorker.fixedBackOffDelay}
        resources:
          limits:
            cpu: ${engine.vcpus}
            memory: ${engine.ram}Gi
          requests:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: payload
          mountPath: payload.json
          subPath: payload.json
          readOnly: true
      volumes:
      - name: payload
        configMap:
          name: payload
