# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  image:
    tag: ${engine.engineVersion}
  elasticsearch:
    disableExporter: false
zeebe:
  resources:
    limits:
      cpu: ${engine.vcpus}
      memory: ${engine.ram}Gi
    requests:
      cpu: ${engine.vcpus}
      memory: ${engine.ram}Gi
  clusterSize: "${engine.clusterSize}"
  partitionCount: "${engine.partitions}"
  replicationFactor: "${engine.replicationFactor}"
  cpuThreadCount: ${engine.cpuThreadPoolSizeNode}
  ioThreadCount: ${engine.ioThreadPoolSizeNode}
  persistenceType: ${engine.diskType}
  pvcSize: ${engine.diskSize}Gi
  pvcStorageClassName: ssd
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_EXPERIMENTAL_DISABLEEXPLICITRAFTFLUSH
      value: "${engine.disableExplicitRaftFlush}"
    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_BACKPRESSURE_USEWINDOWED
      value: "${engine.bpUseWindowed}"
    - name: ZEEBE_BROKER_BACKPRESSURE_ALGORITHM
      value: "${engine.backPressureAlgorithm}"
    - name: ZEEBE_BROKER_BACKPRESSURE_FIXED_LIMIT
      value: "${engine.initialLimit}"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT
      value: "${engine.initialLimit}"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA
      value: "${engine.vegasAlpha}"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA
      value: "${engine.vegasBeta}"
    - name: ZEEBE_BROKER_BACKPRESSURE_GRADIENT_MINLIMIT
      value: "${engine.minLimit}"
    - name: ZEEBE_BROKER_BACKPRESSURE_GRADIENT_INITIALLIMIT
      value: "${engine.initialLimit}"
    - name: ZEEBE_BROKER_BACKPRESSURE_GRADIENT_RTTTOLERANCE
      value: "${engine.rttTolerance}"
zeebe-gateway:
  replicas: ${gateway.replicas}
  resources:
    limits:
      cpu: ${gateway.vcpus}
      memory: ${gateway.ram}Gi
    requests:
      cpu: ${gateway.vcpus}
      memory: ${gateway.ram}Gi
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
      value: "${gateway.numberOfThreads}"
prometheusServiceMonitor:
  enabled: true
elasticsearch:
  enabled: ${elasticSearch.enabled}
  replicas: ${elasticSearch.clusterSize}
  resources:
    limits:
      cpu: ${elasticSearch.vcpus}
      memory: ${elasticSearch.ram}Gi
    requests:
      cpu: ${elasticSearch.vcpus}
      memory: ${elasticSearch.ram}Gi
