apiVersion: v1
kind: Service
metadata:
  name: camunda-zeebe-gateway-headless
  labels:
    app: camunda-platform
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: zeebe-gateway
spec:
  clusterIP: None  # This makes it a headless service
  type: ClusterIP
  selector:
    app: camunda-platform
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/instance: camunda
    app.kubernetes.io/part-of: camunda-platform
    app.kubernetes.io/component: zeebe-gateway
  ports:
    - name: grpc
      port: 26500
      targetPort: 26500
      protocol: TCP
      appProtocol: kubernetes.io/h2c
