apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-ext4
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Delete