apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 6
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/zeebe-io/worker:SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTIONS
            value: >-
              -Dapp.brokerUrl=falko-***REMOVED***-zeebe-gateway:26500
              -Dzeebe.client.requestTimeout=62000
              -Dapp.worker.cap***REMOVED***ty=120
              -Dapp.worker.pollingDelay=1ms
              -Dapp.worker.completionDelay=10ms
              -Dapp.worker.completeJobsAsync=true
              -Dapp.worker.payloadPath=bpmn/small_payload.json
              -XX:+HeapDumpOnOutOfMemoryError
          - name: LOG_LEVEL
            value: "warn"
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zeebe
    app.kubernetes.io/instance: ${namespace}
    app.kubernetes.io/name: zeebe-cluster
  name: worker
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  publishNotReadyAddresses: true
  selector:
    app: worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
