apiVersion: batch/v1
kind: Job
metadata:
  name: zbctl-deploy
spec:
  template:
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: t3-medium
      containers:
      - name: zbctl-deploy
        image: ${engine.image}
        command: ["sh", "-c", "zbctl --host camunda-zeebe-gateway --insecure deploy resource /models/*.*mn"]
        volumeMounts:
        - name: models
          mountPath: /models
          readOnly: true
      volumes:
      - name: models
        configMap:
          name: models
      restartPolicy: Never
