server:
  port : 8082
ccb:
  bpmnfile: ***REMOVED***.bpmn
google:
  sheetId: ***REMOVED***
  inputs: A1:BI
  oauth:
    clientid: ***REMOVED***
    clientsecret: ***REMOVED***
    callbackPort: 8888
    username: ***REMOVED***
kube:
  namespace: camunda
  region: us-east-1