server:
  port : 8075
ccb:
  bpmnfile: EightTasks.bpmn
google:
  sheetId: xxxx
  inputs: A1:BX
  oauth:
    clientid: xxxx
    clientsecret: xxxx
    callbackPort: xx
    username: xx@xx.com
kube:
  namespace: camunda
  region: us-east-1