server:
  port : 8075
ccb:
  bpmnfile: EightTasks.bpmn
google:
  sheetId: 1wAYwnktT_nHwfm_7YJxGrP8joHOPn8T6SliwbFd_UK4
  inputs: A1:CM
  oauth:
    clientid: 403405972886-ednr3cvd2nl6s4mvmtjh0p1v03lpr6ft.apps.googleusercontent.com
    clientsecret: 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
    callbackPort: 8888
    username: jothikiruthika.viswanathan@camunda.com
kube:
  namespace: camunda
  region: us-east-1