server:
  port : 8082  
google:
  sheetId: ***REMOVED***
  inputs: A1:C
  oauth:
    clientid: XXX.apps.googleusercontent.com
    clientsecret: ***REMOVED***
    callbackPort: 8888
    username: XXX@camunda.com
kube:
  prefix: christophe
  region: us-east-1