server:
  port : 8082
ccb:
  bpmnfile: EightTasks.bpmn
google:
  sheetId: <YOUR_GOOGLE_SHEET_ID>
  inputs: A1:CB
  oauth:
    clientid: <YOUR_GOOGLE_CLIENT_ID>.apps.googleusercontent.com
    clientsecret: <YOUR_GOOGLE_CLIENT_SECRET>
    callbackPort: 8888
    username: <YOUR_GOOGLE_USERNAME>
kube:
  namespace: camunda
  region: us-east-1