server:
  port : 8082
ccb:
  bpmnfile: ***REMOVED***.bpmn
google:
  sheetId: ***REMOVED***
  inputs: A1:BH
  oauth:
    clientid: XXX.apps.googleusercontent.com
    clientsecret: ***REMOVED***
    callbackPort: 8888
    username: XXX@camunda.com
kube:
  namespace: falko-***REMOVED***
  region: us-east-1