server:
  port : 8082  
google:
  sheetId: 1y6EP1PcftdchClBFHIRbhHG510vWzS9sweJcaOWSItI
  inputs: A2:BH
  oauth:
    clientid: XXX.apps.googleusercontent.com
    clientsecret: GOCSPX-XXX
    callbackPort: 8888
    username: XXX@camunda.com
kube:
  namespace: falko-dtcc
  region: us-east-1