# Chart values for the Camunda Platform 8 Helm chart.
# This file deliberately contains only the values that differ from the defaults.
# For changes and documentation, use your favorite diff tool to compare it with:
# https://github.com/camunda/camunda-platform-helm/blob/main/charts/camunda-platform/values.yaml

global:
  image:
    tag: latest
  elasticsearch:
    disableExporter: true
zeebe:
  resources:
    limits:
      cpu: 5
      memory: 18Gi
    requests:
      cpu: 5
      memory: 18Gi
  clusterSize: "126"
  partitionCount: "210"
  replicationFactor: "3"
  cpuThreadCount: 5
  ioThreadCount: 1
  persistenceType: memory
  pvcSize: 128Gi
  pvcStorageClassName: ssd
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_EXPERIMENTAL_DISABLEEXPLICITRAFTFLUSH
      value: "true"
  affinity:
    podAntiAffinity: {}
zeebe-gateway:
  image:
    repository: gcr.io/camunda-researchanddevelopment/roman-zeebe
    tag: roman.1
  replicas: 3
  resources:
    limits:
      cpu: 15
      memory: 27Gi
    requests:
      cpu: 15
      memory: 27Gi
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
      value: "15"
    - name: ZEEBE_GATEWAY_EXPERIMENTAL_MAXJOBSTOACTIVATEPERPARTITION
      value: "0"
operate:
  enabled: false
tasklist:
  enabled: false
optimize:
  enabled: false
prometheusServiceMonitor:
  enabled: true
identity:
  enabled: false
elasticsearch:
  enabled: false
